---
- name: Configure servers & routers
  hosts: all
  become: true
  tasks:

    - name: Set up NAT on inetRouter
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "templates/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")


    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: disable default route
      ansible.builtin.copy: 
       src: "templates/00-installer-config.yaml"
       dest: "/etc/netplan/00-installer-config.yaml"
       owner: root
       group: root
       mode: 0644
      when: (ansible_hostname != "inetRouter") 

    - name: add default gateway for centralRouter
      template: 
       src: "templates/50-vagrant_{{ansible_hostname}}.yaml"
       dest: /etc/netplan/50-vagrant.yaml
       owner: root
       group: root
       mode: 0644

    - name: Description
      ansible.builtin.apt:
       name: traceroute
       update_cache: yes

    - name: restart all hosts
      reboot:
       reboot_timeout: 600



      



